project:
  name: Amerihealth Caritas VIP Care
  slug: amerihealth_caritas_vip_de
  description: Medicaid plans for DE, FL, PA
  version: "1.0"

site:
  domain: amerihealthcaritasvipcare.healthsparq.com
  brand_code: AVIPC
  insurer_code: AVIPC_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - DE
    - FL
    - PA

concurrency:
  max_workers: 25
  max_browsers: 25
