project:
  name: Amerihealth NJ
  slug: amerihealth_nj
  description: Commercial NG plans for NJ, DE, PA
  version: "1.0"

site:
  domain: web.healthsparq.com
  brand_code: IBXREDAHNJCOMMNG
  insurer_code: IBXRED_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - NJ
    - DE
    - PA

concurrency:
  max_workers: 25
  max_browsers: 25
