project:
  name: Amerihealth Administrators PA
  slug: amerihealth_administrators_pa
  description: AHA plans for PA, NJ
  version: "1.0"

site:
  domain: ibx.healthsparq.com
  brand_code: IBXREDAHA
  insurer_code: IBXRED_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - PA
    - NJ

concurrency:
  max_workers: 25
  max_browsers: 25
