project:
  name: Asuris Northwest
  slug: asuris_northwest
  description: Plans for WA, OR, ID, UT
  version: "1.0"

site:
  domain: web.healthsparq.com
  brand_code: AS
  insurer_code: AS_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - WA
    - OR
    - ID
    - UT

concurrency:
  max_workers: 25
  max_browsers: 25
