project:
  name: Excellus BCBS
  slug: excellus
  description: Blue Cross Blue Shield of NY
  version: "1.0"

site:
  domain: excellusbcbs.healthsparq.com
  brand_code: EXC
  insurer_code: EXC_I
  api_version: v4
  auth_url_pattern: "/#/one/"

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - NY

concurrency:
  max_workers: 25
  max_browsers: 25
