project:
  name: Select Health of SC
  slug: first_choice_sc
  description: Medicaid plans for SC
  version: "1.0"

site:
  domain: selecthealthofsc.healthsparq.com
  brand_code: SHSC
  insurer_code: SHSC_I
  api_version: v4

plans:
  - product_code: "2400"
    name: Select Health Medicaid

coverage:
  states:
    - SC

concurrency:
  max_workers: 25
  max_browsers: 25
