project:
  name: Highmark Wholecare
  slug: highmark_wholecare
  description: Medicaid and Medicare plans for PA
  version: "1.0"

site:
  domain: hmwholecare.healthsparq.com
  brand_code: GWMCAID
  insurer_code: GW_I
  api_version: v4

plans:
  - product_code: all
    name: All Medicaid Plans
    brand_code: GWMCAID
  - product_code: all
    name: All Medicare Plans
    brand_code: GWMCARE

coverage:
  states:
    - PA

concurrency:
  max_workers: 25
  max_browsers: 25
