project:
  name: Maine Community Health Options
  slug: maine_community_health_options
  description: ACA plans for ME
  version: "1.0"

site:
  domain: healthoptions.healthsparq.com
  brand_code: CHO
  insurer_code: CHO_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - ME

concurrency:
  max_workers: 25
  max_browsers: 25
