project:
  name: Medical Mutual
  slug: medical_mutual
  description: Plans for OH and surrounding states
  version: "1.0"

site:
  domain: medmutual.healthsparq.com
  brand_code: SMN
  insurer_code: MMO_I
  api_version: v4

plans:
  - product_code: "01"
    name: SuperMed Network

coverage:
  states:
    - OH

concurrency:
  max_workers: 25
  max_browsers: 25
