project:
  name: Medica SG
  slug: medica_sg
  description: ACA Small Group plans for Midwest
  version: "1.0"

site:
  domain: medica.healthsparq.com
  brand_code: MEDICA
  insurer_code: MEDICA_I
  api_version: v4
  auth_url_pattern: "/#/one/"

plans:
  - product_code: "735"
    name: Altru & You with Medica
    states: [SD, ND, WI, MN]
  - product_code: "752"
    name: Clear Value with Medica
    states: [SD, ND, WI, MN]
  - product_code: "740"
    name: Essentia Choice Care with Medica
    states: [SD, ND, WI, MN]
  - product_code: "035"
    name: Medica Choice Passport with UnitedHealthcare Choice Plus
    states: [SD, ND, WI, MN]
  - product_code: "036"
    name: Medica Choice Passport with UnitedHealthcare Options PPO
    states: [SD, ND, WI, MN]
  - product_code: "728"
    name: Medica CompleteHealth (featuring care at Mayo Clinic)
    states: [SD, ND, WI, MN]
  - product_code: "611"
    name: Medica Elect
    states: [SD, ND, WI, MN]
  - product_code: "699"
    name: Medica Focus
    states: [SD, ND, WI, MN]
  - product_code: HPSN
    name: Medica Health Plan Solutions
    states: [SD, ND, WI, MN]
  - product_code: "716"
    name: Park Nicollet and HealthPartners Medical Group First with Medica
    states: [SD, ND, WI, MN]
  - product_code: "714"
    name: Ridgeview Community Network powered by Medica
    states: [SD, ND, WI, MN]
  - product_code: "742"
    name: VantagePlus with Medica
    states: [SD, ND, WI, MN]
  - product_code: 745MP
    name: VantagePlus with Medica (M Physicians employees)
    states: [SD, ND, WI, MN]
  - product_code: HCMC917
    name: Hennepin Healthcare Horizon Plan or HDHP with HSA
    states: [MN]
  - product_code: HCMC
    name: Hennepin Healthcare Options Plan
    states: [MN]
  - product_code: 736UMA
    name: UMN Altru & You with Medica
    states: [MN]
  - product_code: "100"
    name: UMN Choice Regional
    states: [MN]
  - product_code: "050"
    name: UMN Elect/Essential
    states: [MN]
  - product_code: 741UME
    name: UMN Essentia Choice Care with Medica
    states: [MN]
  - product_code: "101"
    name: UMN Choice National/HSA
    states: [MN]
  - product_code: 729UMC
    name: UMN Medica CompleteHealth
    states: [MN]
  - product_code: 717UMP
    name: UMN Park Nicollet and HealthPartners Medical Group First with Medica
    states: [MN]
  - product_code: 714UMR
    name: UMN Ridgeview Community Network powered by Medica
    states: [MN]
  - product_code: "745"
    name: UMN VantagePlus with Medica
    states: [MN]
  - product_code: CELE
    name: Elevate by Medica
    states: [IA, NE]
  - product_code: CNAT2
    name: Medica Choice National
    states: [IA, NE]
  - product_code: CCHI2
    name: Medica with CHI Health
    states: [IA, NE]

coverage:
  states:
    - WI
    - MN
    - ND
    - SD
    - IA
    - NE

concurrency:
  max_workers: 10
  max_browsers: 10
