project:
  name: Medica
  slug: medica
  description: Individual and Family Business plans for Midwest
  version: "1.0"

site:
  domain: medica.healthsparq.com
  brand_code: IFB
  insurer_code: MEDICA_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - IA
    - MN
    - ND
    - NE
    - SD
    - WI

concurrency:
  max_workers: 25
  max_browsers: 25
