project:
  name: MVP Health
  slug: mvp_health
  description: ACA plans for NY, VT
  version: "1.0"

site:
  domain: mvp.healthsparq.com
  brand_code: MVP
  insurer_code: MVP_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - NY
    - VT

concurrency:
  max_workers: 25
  max_browsers: 25
