project:
  name: Tufts Health Plan
  slug: tufts_health_plans
  description: Plans for MA, NH, RI
  version: "1.0"

site:
  domain: point32health.healthsparq.com
  brand_code: THP
  insurer_code: TUFTS_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - MA
    - NH
    - RI

concurrency:
  max_workers: 25
  max_browsers: 25
