project:
  name: Wellmark
  slug: wellmark
  description: ACA plans for IA, SD
  version: "1.0"

site:
  domain: web.healthsparq.com
  brand_code: WELLMARK
  insurer_code: WMRK_I
  api_version: v4

plans:
  - product_code: all
    name: All Plans

coverage:
  states:
    - IA
    - SD

concurrency:
  max_workers: 25
  max_browsers: 25
